apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: dev-ingress
spec:
  rules:
    - host: dev.wp.k8s-5.sa
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress
              servicePort: 80
