apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wp-dev
nameSuffix: -dev
resources:
- ../../base/wordpress
- namespace.yaml
transformers:
- labels.yaml
patchesStrategicMerge:
- dev-ingress.yaml
images:
- name: wordpress
  newTag: 5.7-php8.0-apache

