apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-dev
nameSuffix: -dev
resources:
- ../../bases/wordpress
- namespace.yaml
transformers:
- labels.yaml
images:
- name: wordpress:5-php7.4-apache
  newTag: 5.7-php7.4-apache
