apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.37.105
    path: "/mnt/IT-Academy/nfs-data/sa2-16-21/Burmeistser/wordpress"
