apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
        - mysql-service.yaml
        - pvc-mysql.yaml
        - pvc-wordpress.yaml
        - pv-nfs.yaml
        - pv-nfs-db.yaml
        - secret.yaml
        - wordpress-deploy.yaml
        - wordpress-service.yaml
        - ingress.yaml
        - mysql-deploy.yaml

images:
  - name: wordpress
    newTag: 5-php7.4-apache
