apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wp-prd
nameSuffix: -prd
resources:
- ../../base/wordpress
- namespace.yaml
transformers:
- labels.yaml

images:
- name: wordpress
  newTag: 5.7-php7.4-apache
  
patchesStrategicMerge:  
- prd-ingress.yaml  
