apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: prd-ingress
spec:
  rules:
    - host: prd.wp.k8s-5.sa
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress
              servicePort: 80
